### ISSUE TITLE
Add modification functionality to `POST` handler for `register`

### ISSUE THREAD

**Issue by xav** [WalletConnect/gilgamesh#60]
Add a `PUT` handler to the `register` endpoint to append/remove tags from existing subscriptions.

**Comment by devceline** [comment]
> Add a `PUT` handler to the `register` endpoint to append/remove tags from existing subscriptions.

Maybe my initial proposal was a bit too hasty. Currently `POST` to register tags fails when tags are already registered with that specific client id. Let's just remove that failure and adjust the body like so

can we just make the body of the post the following:
```
{
  tags: number[] // completely overwrite registered tags, add them if they don't exist, remove any not on the list,
  appendTags: number[] // purely additive - duplicates are ignored
  removeTags: number[] // purely subtractive -  subtracting a nonexisting tag fails silently 
}
```

**Comment by xav** [comment]
@devceline Which one takes precedence if a tag is both in `appendTags` and `removeTags`?

**Comment by devceline** [comment]
> @devceline Which one takes precedence if a tag is both in `appendTags` and `removeTags`?

We should throw an error informing the sender that they have conflicting modifications
